proxy:
  secretToken: null
hub:
  image:
    name: jupyterhub/k8s-hub
    tag: 4.3.1
  extraEnv: {}
singleuser:
  image:
    name: jupyter/base-notebook
    tag: latest
  memory:
    limit: 1G
    guarantee: 512M
  cpu:
    limit: 1
    guarantee: 0.5
  storage:
    type: dynamic
    capacity: 1Gi

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - jupyter.local   
  tls:
    - secretName: homelab-tls
      hosts:
        - jupyter.local    

rbac:
  create: true

