alertmanager:
  persistentVolume:
    storageClass: local-path
    enabled: true
    size: 5Gi
server:
  persistentVolume:
    storageClass: local-path
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 0.5
      memory: 1Gi
service:
  type: LoadBalancer
crds:
  create: false
